server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Book
          uri: http://localhost:8081
          predicates:
            - Path=/books/** 
        - id: Reservation
          uri: http://localhost:8082
          predicates:
            - Path=/reservations/** 
        - id: Rental
          uri: http://localhost:8083
          predicates:
            - Path=/rentals/** 
        - id: Notice
          uri: http://localhost:8084
          predicates:
            - Path= 
        - id: MyPage
          uri: http://localhost:8085
          predicates:
            - Path= /myPages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Book
          uri: http://Book:8080
          predicates:
            - Path=/books/** 
        - id: Reservation
          uri: http://Reservation:8080
          predicates:
            - Path=/reservations/** 
        - id: Rental
          uri: http://Rental:8080
          predicates:
            - Path=/rentals/** 
        - id: Notice
          uri: http://Notice:8080
          predicates:
            - Path= 
        - id: MyPage
          uri: http://MyPage:8080
          predicates:
            - Path= /myPages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
